#the database djdesweb must be created previously

services:
  nodejs_app:
    build: ./nodejs
    container_name: nodejs_app_desweb_1
    command: /bin/sh -c "./start_project.sh"
    restart: "no"
    volumes:
      - ./geoportal:/usr/src/app
    ports:
      - ${NODEJS_FORWARDED_PORT}:5173
    env_file:
      - .env
      - .env.dev
    networks:
      - postgis_postgis
networks:
   postgis_postgis:
      driver: bridge
      external: true

